### ISSUE TITLE
What are the results? Got some cloud files?

### ISSUE THREAD

**Issue by biechifanle** [3DOM-FBK/COLMAP_SLAM#3]
What are the results? Got some cloud files?

**Comment by lcmrl** [comment]
Hi, you can find the trajectories in scaled_keyframes1.txt for cam0 and in scaled_keyframes2.txt for cam1. In ./outs you can find the results in colmap format, so you can directly visualize the results importing the models there

**Comment by biechifanle** [comment]
Hello, can I get the position relative to the camera through your algorithm? That is, the camera's external parameter matrix. What I want to achieve is to convert the feature points, x, y coordinates recognized by the camera into relative world coordinate points based on the camera's internal and external parameter matrix.

**Comment by lcmrl** [comment]
Yes, in the output folder you will find a file named images.txt where you can find the quaternions, so the orientation of each keyframe respect the global reference system, and the translation vector, so the vector that points to the world reference system seen from the camera reference system

**Comment by lcmrl** [comment]
In cloud.txt you can also see the 2D tie points triangulated in 3D and the trajectory of the camera

**Comment by biechifanle** [comment]
Thank you very much for your answer, handsome man. Your answer is very helpful to me.
