### ISSUE TITLE
Stereo COLMAP of two cameras

### ISSUE THREAD

**Issue by JunjieLiuSWU** [3DOM-FBK/COLMAP_SLAM#7]
Hello, I have some questions about COLMAP_SLAM for multi-camera scenario. Does the parameter "BASELINE_CAM0_CAM1" of config.ini only used to restore the scale? Is there any other difference between monocular and stereo COLMAP_SLAM?

**Comment by lcmrl** [comment]
Sorry for the late reply, yes the baseline is mainly used for scaling, that is not a small problem for mono =)
