### ISSUE TITLE
I'd like to know how to apply absolute coordinates.

### ISSUE THREAD

**Issue by This2sStone** [3DOM-FBK/COLMAP_SLAM#8]
Hello, I am a frequent user of COLMAP SLAM. I noticed that the metadata for each image includes latitude, longitude, and altitude coordinates. I believe incorporating these coordinates could result in a more accurate SLAM implementation. Is there a way to apply this?

**Comment by lcmrl** [comment]
Hi, sure I planned to finish that part but still busy on some other projects. For sure it will help, I suggest to add GPS as constraint at the end of the processing. You can use this very interesting project https://github.com/Vincentqyw/colmap-gps
So GPS positions have to be written as priors in the database and run the BA with constraints. If you want to collaborate on this, feel free to pull your changes!

**Comment by This2sStone** [comment]
Thank you very much for the kind and detailed response. I'll give it a try!
